banner:
  location: 
    classpath:/text/banner.txt
server:
  error:
    whitelabel:
      enabled: false  
    path: /error
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectmanagertools?useSSL=false
    username: root
    password: Dxc2018 
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update  
      naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy  
    show-sql: false 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
//logging:
//  level:
//    org.hibernate.SQL: DEBUG
//   org.hibernate.type: TRACE
// url: jdbc:mysql:// ec4w01735.itcs.entsvcs.net:3306/pmtool?useSSL=false
//    username: root
//    password: AMS.SEAT.Root-01