banner:
  location: 
    classpath:/text/banner.txt
server:
  error:
    whitelabel:
      enabled: false  
    path: /error
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/projectmanagertools?useSSL=false
    username: root
    password: badalona1972 
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update  
      naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy  
    show-sql: false 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false